<!-- Home Page -->
    	<div data-role="page" data-theme="e" id="home">
    		<div data-role="header" data-theme="e" data-fullscreen="false" data-position="fixed">
    			<h1><img src="<?php echo base_url();?>images/header.png" /></h1>   	
	    			<nav data-role="navbar">
	    			<ul>
	    				<li><a href="#" data-icon="home" class="ui-btn-active ui-state-persist" id="home" 
                        	data-transition="none">Home</a></li>
	    				<li><a href="<?php echo base_url();?>index.php/home/about" data-icon="info" id="about" data-transition="none">About Us</a></li>
	    				<li><a href="<?php echo base_url();?>index.php/home/contact" data-icon="info" id="contact" data-transition="none">Contact Us</a></li>
	    				<li><a href="php_script/login.php" data-icon="arrow-r" id="login" data-transition="none">Login</a></li>
	    			</ul>
	    			</nav>	   
    		</div>
   		  <div data-role="content" data-theme="e">  
			<p><strong>St. Michael's College</strong> is a school in <a href="http://en.wikipedia.org/wiki/Iligan_City" title="Iligan City">Iligan City</a>, <a href="http://en.wikipedia.org/wiki/Philippines" title="Philippines">Philippines</a>. It is a <a href="http://en.wikipedia.org/wiki/Roman_Catholicism" title="Roman Catholicism">Catholic</a> and RVM (Religious of The Virgin Mary) institution of higher learning founded as a catechetical center by Rev. Fr. Felix Cordova, S.J., in 1914. It is presently administered by the RVM Sisters, offering four levels of education: Elementary, Secondary, Tertiary, Graduate School and Short Term Courses.</p>
			<p>The School was Founded as a catechetical center by Rev. Fr. Felix Cordova, SJ in 1914. It was then formally established as Escuela de San Miguel in the year 1915, in honor of Iligan's Patron Saint, St. Michael the Archangel. The <a href="http://en.wikipedia.org/wiki/Religious_of_the_Virgin_Mary" title="Religious of the Virgin Mary">Religious of the Virgin Mary</a> sisters were then invited to teach at the Escuela with Rev. Mo. Ma Micaela Cuenca, RVM as the first superior and principal. Since then the RVM Sisters have run the School. The School had a gone a long way to become St. Michael's Academy in 1938 and St. Michael's College in 1952 when it Attained Full Collegiate Status.</p>
			<p>Distinguished as the oldest catholic instituition of Higher Lerning in Lanao area, St. Michael's College continues to grow in leaps and bounds as manifested in physical structures, organizational capabilities, courses offered and services rendered to the community. This is well-indicated in the school's attainment for <a href="http://en.wikipedia.org/wiki/PAASCU" title="PAASCU">Philippine Accrediting Association of Schools, Colleges and Universities</a> Accreditation for the Grade School, High School and the three collegiate programs namely, Arts and Science, Education and Business Administration. It's Philosophy of Objectives, Mission and Vision anchored on the teaching of Christ and the Catholic Church provide the substance of its Core Values, Goal and Objectives. Now on its active bid to become the city's first Private Catholic University and the Third RVM School in Northern Mindanao, Saint Michael's College of Iligan currently offers 7 disciplines: Business Administration, Hotel and Restaurant Management, Accountancy, Engineering and Information Technology, Nursing, Criminology, Education, Arts and Sciences and the Basic Education. It also offers the TESDA Ladderized Courses and the education - related Graduate Studies Program. SMC is currently expanding its infrastructures to support the growing needs of the academic community and even to the City of Iligan.</p>					
            </div>